package pt.josegamerpt.quemeareferencia;

import java.util.HashMap;

public class Values {

    static HashMap<Integer, String> refs = new HashMap<>();

    public static void load() {
        refs.put(10003, "Lycamobile Portugal, Lda");
        refs.put(10061, "NOS Comunicações SA");
        refs.put(10081, "OTLIS, Operadores de Transportes Região de Lisboa ACE");
        refs.put(10083, "TIP,Transportes Intermodais Porto ACE");
        refs.put(10095, "Pagamentos ao Estado");
        refs.put(10121, "ACP, Automóvel Clube de Portugal");
        refs.put(10128, "Fidelidade Companhia Seguros SA");
        refs.put(10130, "Eden Springs Portugal SA");
        refs.put(10131, "TAP, Transportes Aéreos Portugueses");
        refs.put(10132, "Liberty Seguros");
        refs.put(10142, "Universidade do Minho");
        refs.put(10154, "Medis - Companhia Portuguesa de Seguros de Saúde, SA");
        refs.put(10155, "Loja do Condomínio");
        refs.put(10158, "Vodafone Portugal Comunicações Pessoais");
        refs.put(10175, "Seleções Readers Digest");
        refs.put(10196, "FAGAR, Faro, Gestão de Águas e Resíduos");
        refs.put(10208, "Global Noticias, anúncios Jornal de Noticias");
        refs.put(10211, "Câmara Municipal do Porto");
        refs.put(10212, "Motor Press Lisboa, Edição e Distribuição SA");
        refs.put(10227, "Caravela, Companhia de Seguros SA");
        refs.put(10231, "INATEL");
        refs.put(10237, "Publiregiões - Soc. Jornalística Editorial, Lda");
        refs.put(10241, "HiPay: Compra Fácil");
        refs.put(10244, "Victoria Seguros");
        refs.put(10261, "OK TeleSeguros");
        refs.put(10271, "Ordem dos Médicos");
        refs.put(10277, "NOS Comunicações ");
        refs.put(10294, "AGEAS Portugal Companhia Seguros SA");
        refs.put(10296, "Faculdade de Motricidade Humana");
        refs.put(10297, "Vodafone Portugal");
        refs.put(10311, "Ordem dos Engenheiros");
        refs.put(10314, "IPCV, Instituto Politécnico de Viana do Castelo");
        refs.put(10335, "Ordem dos Enfermeiros");
        refs.put(10351, "NOS Madeira Comunicações");
        refs.put(10363, "FNAC");
        refs.put(10377, "MAPFRE Seguros Gerais, S.A.");
        refs.put(10404, "COFAC, Cooperativa Formação e Animação Cultural");
        refs.put(10411, "Certiel, Associação Certificador Instalações Eletricas");
        refs.put(10420, "Fidelidade Companhia Seguros SA");
        refs.put(10422, "INCM");
        refs.put(10451, "ISEP, Instituto Superior de Engenharia do Porto");
        refs.put(10455, "Liberty Seguros, SA");
        refs.put(10482, "FC Porto cotas (Sportinveste Multimedia SA)");
        refs.put(10511, "Porto Editora, Escola Virtual");
        refs.put(10550, "OTIS Elevadores Lda");
        refs.put(10559, "Ifthenpay (pequenas empresas e particulares)");
        refs.put(10575, "Viagens Abreu");
        refs.put(10587, "INPI - Instituto Nacional da Propriedade Industrial ");
        refs.put(10597, "CUF Hospitais");
        refs.put(10611, "EasyPay (pequenas empresas e particulares)");
        refs.put(10612, "Sweets 4 U, COM. E REP.PROD.ALIM.LDA");
        refs.put(10641, "Instituto de Gestão Financeira e de Infra-Estruturas da Justiça, IP");
        refs.put(10644, "Cloudware, Toconline (Programas de faturação)");
        refs.put(10652, "SAGE Portugal");
        refs.put(10828, "Nestlé Portugal SA");
        refs.put(10941, "Agência de Gestão da Tesouraria e da Dívida Pública - IGCP, E.P.E");
        refs.put(10950, "IVV, Instituto da Vinha e do Vinho");
        refs.put(10954, "Altice Portugal (PT MEO)");
        refs.put(10958, "ISEP, Instituto Superior de Engenharia do Porto");
        refs.put(10982, "Armazéns Marques Soares (Porto)");
        refs.put(10991, "STAPLES Portugal SA - Equip. Escritório");
        refs.put(10996, "ADENE, Agência para a Energia");
        refs.put(11012, "Instituto de Registos e Notariado, IP");
        refs.put(11013, "Portal da Empresa, AMA, Agência para a Modernização Administrativa");
        refs.put(11024, "Lusopay, (atribuição de referencias MB a pequenas empresas e particulares: Funidelia)");
        refs.put(11034, "Fidelidade Companha de Seguros, SA.");
        refs.put(11056, "N Seguros");
        refs.put(11062, "ACP Mediação de Seguros SA");
        refs.put(11063, "Seguradoras Unidas, SA");
        refs.put(11100, "Clínica CUF Cascais, SA.");
        refs.put(11163, "Villas Boas ACP Archer & Camacho, SA");
        refs.put(11202, "Ifthenpay (pequenas empresas e particulares)");
        refs.put(11206, "Agência para a Modernização Administrativa");
        refs.put(11216, "Município de Estremoz");
        refs.put(11241, "La Redoute");
        refs.put(11249, "HiPay, Compra Fácil HPME SA (Conforama, HiMedia Lap2Go.pt, GlobalSport.pt, Mister Auto, PCDIGA, Betfair, bet365, burlas OLX)");
        refs.put(11283, "EDP");
        refs.put(11286, "Hospital da Luz, SA.");
        refs.put(11299, "AT, Autoridade Tributária, Pagamento IES, Informação Empresarial Simplificada");
        refs.put(11302, "Webnode");
        refs.put(11314, "ONSALESIT SA");
        refs.put(11335, "Athenas Mediadora de seguros");
        refs.put(11358, "Universidade de Coimbra");
        refs.put(11364, "Endesa (Electricidade)");
        refs.put(11369, "Empark Portugal, Empreendimentos e Exploração de Parqueamentos");
        refs.put(11390, "2B Style Unipessoal Lda");
        refs.put(11409, "Courlux Internacional");
        refs.put(11412, "FixeAds, Imovirtual e Standvirtual,  pagamento de anúncios");
        refs.put(11413, "TAP, Transportes Aéreos Portugueses");
        refs.put(11419, "Opensoft Soluções Informáticas SA");
        refs.put(11421, "Câmara Municipal de Lisboa");
        refs.put(11440, "ISEP, Carregamento Cartão Alimentação");
        refs.put(11454, "Direção-Geral da Administração da Justiça, DGAJ ");
        refs.put(11456, "Gold Energy, Comercializadora Energia SA");
        refs.put(11471, "TAP, Transportes Aéreos Portugueses");
        refs.put(11473, "Ifthenpay (pequenas empresas e particulares)");
        refs.put(11496, "Universidade do Porto");
        refs.put(11583, "Gas Natural Serviços SDG SA");
        refs.put(11589, "Worten Equipamentos para o lar, S.A.");
        refs.put(11604, "Ifthenpay (pequenas empresas e particulares)");
        refs.put(11606, "CIF, Agência de Viagens e Turismo SA");
        refs.put(11609, "ISCSP, Instituto Superior de Ciências Sociais e Politicas");
        refs.put(11644, "Iberdrola Energia");
        refs.put(11648, "IGFIJ, Instituto de Gestão Financeira e Equipamentos da Justiça");
        refs.put(11663, "Município de Santo Tirso");
        refs.put(11668, "Move Aveiro");
        refs.put(11669, "Multicert, Serviços de Certificação Eletrónica, SA");
        refs.put(11679, "AEFDTV, Associação Educação Física Desportiva de Torres Vedras");
        refs.put(11683, "Easypay  (pequenas empresas e particulares)");
        refs.put(11686, "Ifthenpay (Castro Eletrónica, outras pequenas empresas e particulares)");
        refs.put(11687, "Ifthenpay, (Audilar, Rádio Popular)");
        refs.put(11693, "Centro Hospitalar e Universitário de Coimbra");
        refs.put(11703, "Diário de Aveiro");
        refs.put(11706, "Universidade de Lisboa");
        refs.put(11708, "MHR");
        refs.put(11711, "IRN, Instituto de Registos e Notariado, IP");
        refs.put(11712, "IRN, Instituto de Registos e Notariado, IP");
        refs.put(11713, "IRN, Instituto de Registos e Notariado, IP");
        refs.put(11714, "IRN, Instituto de Registos e Notariado, IP");
        refs.put(11717, "IEFP, Instituto de Emprego e Formação Profissional");
        refs.put(11726, "Vertbaudet Portugal, Lda. Bimbi.");
        refs.put(11737, "Ticket Restaurant");
        refs.put(11749, "SportZone");
        refs.put(11758, "SATA Internacional");
        refs.put(11767, "CVRVV, Comissão de Viticultura da Região Vinhos Verdes");
        refs.put(11768, "Câmara Municipal de Viana do Castelo");
        refs.put(11780, "Claranet Soho, SA");
        refs.put(11782, "Easypay (pequenas empresas e particulares)");
        refs.put(11795, "Instituto dos Registos e do Notariado (Registo Predial Online, RPO)");
        refs.put(11799, "IRN, Instituto dos Registos e do Notariado (Registo Predial Online, RPO)");
        refs.put(11802, "Ifthenpay");
        refs.put(11811, "Centro Social da Legião da Boa Vontade");
        refs.put(11843, "Easypay (pequenas empresas e particulares)");
        refs.put(11846, "Iberdrola");
        refs.put(11852, "PPRO Financial Ltd.");
        refs.put(11854, "PPRO FINANCIAL LTD (pequenas empresas e particulares)");
        refs.put(11873, "Ifthenpay (pequenas empresas e particulares)");
        refs.put(11877, "euPago (Instituição de Pagamento Lda, Invoice Express)");
        refs.put(11893, "HPME SA (pequenas empresas e particulares)");
        refs.put(11896, "IAVE, Instituto de Avaliação Educativa");
        refs.put(11916, "Via Verde Portugal, S.G.E. Cobranças SA");
        refs.put(11925, "Ifthenpay (pequenas empresas e particulares)");
        refs.put(11937, "IRN, Instituto Registos Notariado, IP");
        refs.put(11944, "Via Verde Portugal, S.G.E. Cobrancas SA");
        refs.put(11950, "Câmara Municipal de Lisboa");
        refs.put(11967, "Ifthenpay (pequenas empresas e particulares)");
        refs.put(11979, "PayPayUE PAG UNIP Lda");
        refs.put(11985, "Galp Energia, SA");
        refs.put(11988, "Ifthenpay (Audilar, Delikatessen, etc)");
        refs.put(11989, "Ifthenpay (pequenas empresas e particulares)");
        refs.put(11990, "Ifthenpay (Aquário)");
        refs.put(11999, "EPorto, Estacionamentos Públicos do Porto (multas estacionamento)");
        refs.put(12009, "Gold Energy");
        refs.put(12020, "Easypay (pequenas empresas e particulares)");
        refs.put(12029, "HPME SA (Proalojamento, ...)");
        refs.put(12041, "Easypay");
        refs.put(12057, "Dalenys Payment");
        refs.put(12061, "El Corte Inglés, Grandes Armazéns, SA");
        refs.put(12101, "HPME SA; é utilizado tanto pela Decathlon como pela GearBest");
        refs.put(12121, "Endesa Energia, Sucursal Portugal");
        refs.put(12133, "Ifthenpay (CDUP)");
        refs.put(12142, "euPago Instituição de Pagamento LDA");
        refs.put(12177, "Pupycare Unipessoal Lda.");
        refs.put(12179, "Ifthenpay (Loja das Peças)");
        refs.put(12240, "Câmara Municipal de Aveiro");
        refs.put(12307, "Brigoffice.pt");
        refs.put(12385, "Iberdrola");
        refs.put(20108, "Wizink Bank, SA");
        refs.put(20130, "Novo Banco");
        refs.put(20145, "Sporting Clube de Portugal, Futebol SAD");
        refs.put(20152, "Sporting Clube de Portugal");
        refs.put(20160, "Jogos Santa Casa");
        refs.put(20173, "Liberty Seguros, SA");
        refs.put(20174, "EDP Comercial (Electricidade)");
        refs.put(20175, "Allianz (Seguros)");
        refs.put(20181, "IGFSS, Instituto de Gestão Financeira da Segurança Social");
        refs.put(20183, "Generali, Companhia de Seguros");
        refs.put(20185, "BNP Paribas Personal Finance");
        refs.put(20223, "Novo Banco SA.");
        refs.put(20229, "GE Consumer Finance IFIC SA.");
        refs.put(20237, "Ordem dos Solicitadores e Agentes de Execução, Execuções Fiscais");
        refs.put(20341, "Via Verde, S.G.E. Cobranças SA");
        refs.put(20394, "Millenium BCP Banco Comercial Português");
        refs.put(20409, "Federação Portuguesa de Futebol");
        refs.put(20414, "BEST, Banco Electrónico Serviço Total");
        refs.put(20420, "Metlife Europe Limited");
        refs.put(20426, "FCPorto Lugar Anual (Porto Comercial SA)");
        refs.put(20442, "NOS (antiga ZON e Optimus, Inativo)");
        refs.put(20456, "Crédito Agrícola, Cartões");
        refs.put(20484, "Caixa Geral de Depósitos (ex. carregamento de cartões de débito pré pagos)");
        refs.put(20498, "Banco Santander Consumer Portugal, SA");
        refs.put(20601, "BNP Paribas Personal Finance");
        refs.put(20603, "Optimus / Clix");
        refs.put(20641, "Serviços Municipalizados de Loures, Águas (eventualmente utilizado também por outros municípios)");
        refs.put(20659, "Zurich Seguros");
        refs.put(20669, "Município Oliveira de Azeméis");
        refs.put(20670, "Banco Santander Totta SA");
        refs.put(20678, "ONEY / Jumbo");
        refs.put(20691, "SMAS de Sintra");
        refs.put(20698, "Ordem dos Arquitetos");
        refs.put(20715, "BPI, Banco Português de Investimento");
        refs.put(20718, "Banco Santander Totta");
        refs.put(20719, "Associação DNS PT");
        refs.put(20724, "ACP, Autoridade para as Condições de Trabalho");
        refs.put(20725, "Instituto Politécnico de Portalegre");
        refs.put(20741, "Credibom, Soc. Fin. Aquisições a Crédito, SA");
        refs.put(20754, "Banco Santander Totta, Cartão de crédito");
        refs.put(20755, "Banco Santander Totta SA.");
        refs.put(20776, "AGEAS Portugal Companhia de Seguros SA");
        refs.put(20804, "UNICRE, Instituição Financeira Crédito SA;");
        refs.put(20811, "EPAL, Empresa Portuguesa das àguas Livres, Águas de Lisboa");
        refs.put(20812, "EDP serviço universal");
        refs.put(20813, "BPI, Banco Português de Investimento");
        refs.put(20815, "Águas do Porto");
        refs.put(20820, "DIGAL - Distribuição e Comércio, SA - LPG, Mem Martins");
        refs.put(20821, "IST, Instituto Superior Técnico");
        refs.put(20832, "EEM, Empresa Eletricidade Madeira SA");
        refs.put(20834, "Novo Banco SA");
        refs.put(20838, "ISEG, Instituto Superior de Economia e Gestão");
        refs.put(20839, "Cetelem");
        refs.put(20843, "ANRS, Autoridade Nacional de Segurança rodoviária, multa / coima rodoviária");
        refs.put(20856, "GASCAN, SA.");
        refs.put(20858, "Coficis");
        refs.put(20890, "WIZINK BANK (antigo Barclaycard)");
        refs.put(20891, "WIZINK BANK (antigo Barclaycard)");
        refs.put(20912, "ISPA, Instituto Superior de Psicologia Aplicada");
        refs.put(20918, "Universidade de Aveiro");
        refs.put(20932, "OCC - Ordem dos Contabilistas Certificados");
        refs.put(20934, "Açoreana Seguros");
        refs.put(20936, "NOWO Communications, SA");
        refs.put(20950, "Petrogal, Petróleos de Portugal, SA");
        refs.put(20961, "Rentokill");
        refs.put(20975, "IMTT, Instituto da Mobilidade e dos Transportes Terrestres, IP");
        refs.put(20977, "Remax Portugal (Casax, Consultadoria de Gestão Lda)");
        refs.put(20987, "Bluetickets, Serviços de Bilhética, SA");
        refs.put(21000, "Jet Cooler, Águas e Cafés, SA");
        refs.put(21028, "Banco Santander Totta, SA");
        refs.put(21034, "Banco Primus SA");
        refs.put(21053, "Porto Editora, SA");
        refs.put(21056, "ISFSS, Instituto de Gestão Financeira da Segurança Social");
        refs.put(21086, "IMTT, Instituto da Mobilidade e dos Transportes Terrestres IP");
        refs.put(21094, "Setgás Comercialização, SA.");
        refs.put(21096, "Galp Energia");
        refs.put(21098, "Easypay");
        refs.put(21111, "Instituto Gestão Financeira Segurança Social");
        refs.put(21132, "Águas do Ribatejo");
        refs.put(21135, "Seguradoras Unidas, SA");
        refs.put(21138, "ALLIANZ VIDA");
        refs.put(21142, "Condoarade, Gestão de Condomínios");
        refs.put(21146, "Segurigiene, Saúde no Trabalho SA");
        refs.put(21154, "CTT (Pagamento Portagens)");
        refs.put(21159, "Altice Portugal (PT Empresas, MEO)");
        refs.put(21177, "Galp Gás Natural SA");
        refs.put(21184, "Cofre de Previdência dos Funcionários e Agentes do Estado");
        refs.put(21188, "EDP Soluções Comerciais, SA");
        refs.put(21196, "EDP Soluções Comerciais, SA");
        refs.put(21199, "APECA, Associação das Empresas de Contabilidade e Administração");
        refs.put(21212, "Município de Paredes");
        refs.put(21213, "Universidade Aberta");
        refs.put(21217, "ASCENDI, Auto-Estradas do Norte SA.");
        refs.put(21218, "Ascendi Portagens");
        refs.put(21225, "Montellano Lda");
        refs.put(21323, "321 Crédito, Instituição Financeira de Crédito, SA");
        refs.put(21423, "HPME SA, HI-MEDIA PORTE MONNAIE ÉLECTRONIQUE (HPME) SA, Entidade que faculta serviços de pagamento a terceiros");
        refs.put(21234, "Vialivre (Portagens)");
        refs.put(21235, "OTIS Elevadores, Lda.");
        refs.put(21245, "BMW GMBH Sucursal Portuguesa");
        refs.put(21246, "BMW RENTING PORTUGAL LDA");
        refs.put(21267, "eCalma");
        refs.put(21269, "Universidade do Porto");
        refs.put(21276, "Santander Totta Seguros, Companhia de Seguros de Vida SA");
        refs.put(21286, "Montepio Recuperação de Crédito, Ace");
        refs.put(21297, "Groupama Seguros, SA.");
        refs.put(21309, "Águas da Região de Aveiro - Grupo Águas de Portugal (mas noutros sites está anunciado como Município de Terras de Bouro)");
        refs.put(21312, "Caixa Económica Montepio Geral");
        refs.put(21318, "Município de Coimbra");
        refs.put(21321, "Primavera Software, SA");
        refs.put(21325, "CM Gaia");
        refs.put(21341, "PORTVIAS, Portagem de Vias, SA");
        refs.put(21344, "Município de Gondomar");
        refs.put(21345, "Cascais Próxima, Gestão de Mobilidade, Espaços Urbanos e Energia, EM SA");
        refs.put(21346, "Associação Religiosa dos Custódios de Maria");
        refs.put(21347, "Polícia Municipal de Lisboa");
        refs.put(21365, "Servdebt, Capital Asset Management, Lda.");
        refs.put(21374, "BNP Paribas, Personal Finance, SA");
        refs.put(21375, "Millenium BCP,  Banco Comercial Português");
        refs.put(21383, "Wurth Portugal, Técnica de Montagem, Lda.");
        refs.put(21410, "Servdebt, Capital Asset Management, Lda.");
        refs.put(21417, "Ascendi SA. (Pinhal Interior, Estradas Pinhal)");
        refs.put(21426, "PT Pay SA (Serviços Meo Wallet, TicketLine, outros…)");
        refs.put(21448, "IGFSS, FCT, Fundos de Compensação do Trabalho");
        refs.put(21467, "Liberty Seguros SA");
        refs.put(21487, "Águas de Valongo SA");
        refs.put(21489, "Millennium BCP, Banco Comercial Português");
        refs.put(21523, "Gestifatura, atribuição de referências multibanco");
        refs.put(21496, "CMPEA, Empresa de Águas do Município do Porto EM.");
        refs.put(21535, "Lisgarante, Sociedade de Garantia Mútua, SA");
        refs.put(21540, "Aegon Santander Portugal Vida, Companhia de Seguros");
        refs.put(21546, "UCI, Unión de Créditos Inmobiliários SA");
        refs.put(21544, "Pagamentos a terceiros como Viagra.no");
        refs.put(21557, "CTT, Correios de Portugal (Cobrança de Serviços)");
        refs.put(21559, "Liga Portuguesa contra o Cancro");
        refs.put(21565, "PT Pay SA");
        refs.put(21572, "Victoria Seguros, SA");
        refs.put(21575, "Serviços Municipalizados das Caldas da Rainha");
        refs.put(21577, "Lease Plan Portugal, Comércio e Aluguer de automóveis, Lda.");
        refs.put(21579, "NOS Comunicações SA");
        refs.put(21604, "euPago (Lap2go, organização de eventos como corridas)");
        refs.put(21606, "Ordem dos Enfermeiros");
        refs.put(21607, "CTT Expresso, Serviços Postais Logistica");
        refs.put(21615, "Logicomer, Gestão e Recuperação de Créditos, SA.");
        refs.put(21619, "Serviços Municipalizados de Leiria");
        refs.put(21622, "SMAS, Águas de Coimbra");
        refs.put(21624, "SMAS, Vila Franca de Xira");
        refs.put(21625, "SMAS, Águas da Maia");
        refs.put(21633, "Prio");
        refs.put(21643, "HEFESTO STC, S.A.");
        refs.put(21651, "SMAS, Águas de Gaia");
        refs.put(21653, "SAGASTA, SA.");
        refs.put(21056, "Câmara Municipal do Seixal");
        refs.put(21662, "euPago, Instituição de Pagamento, Lda.");
        refs.put(21691, "Ocidental Seguros ");
        refs.put(21721, "Ifthenpay");
        refs.put(21725, "Hefesto STC, S.A.");
        refs.put(21726, "Galp Power");
        refs.put(21776, "NSeguros");
        refs.put(21799, "EDP Distribuição de Energia, SA.");
        refs.put(21780, "Arrow Global Limited");
        refs.put(21818, "Pode ser da EDP Serviço Universal, S.A, mas pode ser usado para phishing");
        refs.put(21844, "Arrow Global Limited");
        refs.put(21858, "Panorama Jubilante, SA");
        refs.put(23000, "Bet Entertainment Technologies Limited Scrs");
        refs.put(23014, "Blueticket");
        refs.put(23025, "IKEA Portugal Moveis e Decoração, Lda.");
        refs.put(23026, "Odisseias Puras, Viagens e Animação Turistica, S.A.");
        refs.put(23040, "TAP, Transportes Aéreos Portugueses");
        refs.put(23054, "Rede Nacional de Expressos");
        refs.put(23096, "Leroy Merlin");
        refs.put(23144, "PCDIGA");
        refs.put(23154, "Zurich Insurance, Sucursal Portugal");
        refs.put(23565, "E-Redes");

    }

}
